# Generated by mapperPro for the current AuFORApro ADG.
# Host buffers are NumPy arrays; transfer lengths are bytes.
import numpy as np
from typing import List
from test_runif import DeviceConfig, DeviceData, DeviceRuntime, DeviceStream

CONFIG_VALUES = [
    0x2000, 0x1000, 0x00c0,
    0x0000, 0x0000, 0x00c1,
    0x0000, 0x8020, 0x00c2,
    0x0000, 0x0000, 0x00c3,
    0x2400, 0x1000, 0x0100,
    0x0000, 0x0000, 0x0101,
    0x0000, 0x0c20, 0x0102,
    0x0000, 0x0000, 0x0103,
    0x8000, 0x0000, 0x0280,
    0x0030, 0x0000, 0x02c0,
    0x0400, 0x0000, 0x07c0,
    0x0000, 0x0008, 0x0800,
    0xf854, 0x402d, 0x0b40,
    0x2000, 0xaba0, 0x0b41,
    0xffea, 0xefff, 0x0b42,
    0xffef, 0xefff, 0x0b43,
    0xffef, 0xefff, 0x0b44,
    0xffef, 0xefff, 0x0b45,
    0xffef, 0xefff, 0x0b46,
    0x000f, 0x0000, 0x0b47,
    0x0000, 0x0000, 0x0b48,
    0x0000, 0x0000, 0x0b49,
    0x0000, 0x0000, 0x0b4a,
    0x0000, 0x0000, 0x0b4b,
    0x0000, 0x0000, 0x0b4c,
    0x1820, 0x038a, 0x0b4d,
    0x0000, 0x0000, 0x0b4e,
    0x0000, 0x0000, 0x0b4f,
    0x0000, 0x0000, 0x0b50,
    0x0000, 0x0000, 0x0b51,
    0x0000, 0x0000, 0x0b52,
    0x0000, 0xcf00, 0x0b53,
    0xcc12, 0x54f9, 0x0b54,
    0x8b60, 0x8a7c, 0x0b55,
    0xb51b, 0xe0fe, 0x0b56,
    0xffff, 0x007f, 0x0b57,
    0x0000, 0x0100, 0x0b58,
    0x0000, 0x0100, 0x0b59,
    0x0000, 0x0100, 0x0b5a,
    0x0000, 0x0100, 0x0b5b,
    0x0000, 0x0100, 0x0b5c,
    0x0000, 0x0100, 0x0b5d,
    0x0000, 0x0100, 0x0b5e,
    0x0000, 0x0100, 0x0b5f,
    0x0000, 0x0100, 0x0b60,
    0x0000, 0x0100, 0x0b61,
    0x0000, 0x0100, 0x0b62,
    0x0000, 0x0100, 0x0b63,
    0x0000, 0x0100, 0x0b64,
    0x0000, 0x0100, 0x0b65,
    0x0000, 0x0100, 0x0b66,
    0x0000, 0x0100, 0x0b67,
    0x0000, 0x0100, 0x0b68,
    0x0000, 0x0100, 0x0b69,
    0x0000, 0x0100, 0x0b6a,
    0x0000, 0x0100, 0x0b6b,
    0x0000, 0x0100, 0x0b6c,
    0x0000, 0x0100, 0x0b6d,
    0x0000, 0x0100, 0x0b6e,
    0x0000, 0x0100, 0x0b6f,
    0x0000, 0x0100, 0x0b70,
]
IOB_ENABLE = [0xc, 0x0]
TILE_ENABLE = [0x01]

def _input_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    data = np.ascontiguousarray(array).view(np.uint8).reshape(-1)
    if data.nbytes < offset + size:
        raise ValueError(f'input buffer has {data.nbytes} bytes, needs {offset + size}')
    return data[offset:offset + size]

def _output_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    if not isinstance(array, np.ndarray) or not array.flags.c_contiguous:
        raise TypeError('output buffers must be C-contiguous NumPy arrays')
    if not array.flags.writeable or array.nbytes < offset + size:
        raise ValueError(f'output buffer has {array.nbytes} writable bytes, needs {offset + size}')
    return array.view(np.uint8).reshape(-1)[offset:offset + size]

async def aux_stream(
    stream: DeviceStream, config: List[DeviceConfig],
    iptrs: List[DeviceData], idata: List[np.ndarray],
    optrs: List[DeviceData], odata: List[np.ndarray], olen: List[int],
):
    await stream.apply(config)
    await stream.config(config_id=0)
    for ptr, data in zip(iptrs, idata):
        await stream.memcpyHostToDevice(
            d_data=ptr, h_data=data, size=ptr.size
        )
    await stream.execution_start()
    for ptr, data, size in zip(optrs, odata, olen):
        await stream.memcpyDeviceToHost(
            d_data=ptr, h_data=data, size=size
        )
    await stream.release()

async def exp(runtime: DeviceRuntime, input: np.ndarray, output: np.ndarray):
    config_values = list(CONFIG_VALUES)
    iptrs = [
        DeviceData(0x0, 64),  # input + 0 bytes
    ]
    idata = [
        _input_bytes(input, 0, 64),
    ]
    optrs = [
        DeviceData(0x1000, 64),  # output + 0 bytes
    ]
    odata = [
        _output_bytes(output, 0, 64),
    ]
    olen = [64]
    config = DeviceConfig(
        config_values=config_values, iob_en=IOB_ENABLE,
        tile_en=TILE_ENABLE, data_ptr=iptrs + optrs,
    )
    stream = runtime.create_stream()
    await aux_stream(
        stream=stream, config=[config],
        iptrs=iptrs, idata=idata,
        optrs=optrs, odata=odata, olen=olen,
    )
    await stream.synchronize()
