# Generated by mapperPro for the current AuFORApro ADG.
# Host buffers are NumPy arrays; transfer lengths are bytes.
import numpy as np
from typing import List
from test_runif import DeviceConfig, DeviceData, DeviceRuntime, DeviceStream

CONFIG_VALUES = [
    0x0800, 0x0800, 0x0040,
    0x0020, 0x2008, 0x0041,
    0x0800, 0x8040, 0x0042,
    0x0000, 0x0000, 0x0043,
    0x0800, 0x0800, 0x0080,
    0x0020, 0x2008, 0x0081,
    0x0800, 0x1040, 0x0082,
    0x0000, 0x0000, 0x0083,
    0x2000, 0x0800, 0x00c0,
    0xff20, 0x2008, 0x00c1,
    0x0800, 0x8040, 0x00c2,
    0x0000, 0x0000, 0x00c3,
    0x0400, 0x0801, 0x0100,
    0xf920, 0x2008, 0x0101,
    0x08f8, 0x8040, 0x0102,
    0x0000, 0x0000, 0x0103,
    0x0210, 0x0000, 0x0240,
    0x0000, 0x0000, 0x0280,
    0x0000, 0x0000, 0x02c0,
    0x1008, 0x0220, 0x0581,
    0x0001, 0x0000, 0x05c0,
    0x0023, 0x0010, 0x05c1,
    0x0018, 0x00a0, 0x0601,
    0x0008, 0x0000, 0x0780,
    0x0000, 0x0400, 0x07c0,
    0x8000, 0x0001, 0x0cc0,
    0x0000, 0x0002, 0x0d00,
    0x0088, 0x0020, 0x1001,
    0x0000, 0x0000, 0x1002,
    0x0000, 0x0010, 0x1003,
    0x0204, 0x0200, 0x1004,
    0x0000, 0x0000, 0x1005,
    0x0003, 0x0000, 0x1040,
    0x0018, 0x0030, 0x1041,
    0x0000, 0x0000, 0x1200,
]
IOB_ENABLE = [0xf, 0x0]
TILE_ENABLE = [0x01]

def _input_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    data = np.ascontiguousarray(array).view(np.uint8).reshape(-1)
    if data.nbytes < offset + size:
        raise ValueError(f'input buffer has {data.nbytes} bytes, needs {offset + size}')
    return data[offset:offset + size]

def _output_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    if not isinstance(array, np.ndarray) or not array.flags.c_contiguous:
        raise TypeError('output buffers must be C-contiguous NumPy arrays')
    if not array.flags.writeable or array.nbytes < offset + size:
        raise ValueError(f'output buffer has {array.nbytes} writable bytes, needs {offset + size}')
    return array.view(np.uint8).reshape(-1)[offset:offset + size]

async def aux_stream(
    stream: DeviceStream, config: List[DeviceConfig],
    iptrs: List[DeviceData], idata: List[np.ndarray],
    optrs: List[DeviceData], odata: List[np.ndarray], olen: List[int],
):
    await stream.apply(config)
    await stream.config(config_id=0)
    for ptr, data in zip(iptrs, idata):
        await stream.memcpyHostToDevice(
            d_data=ptr, h_data=data, size=ptr.size
        )
    await stream.execution_start()
    for ptr, data, size in zip(optrs, odata, olen):
        await stream.memcpyDeviceToHost(
            d_data=ptr, h_data=data, size=size
        )
    await stream.release()

async def gemm(runtime: DeviceRuntime, inputX: np.ndarray, inputY: np.ndarray, output: np.ndarray):
    config_values = list(CONFIG_VALUES)
    iptrs = [
        DeviceData(0x0, 256),  # inputX + 0 bytes
        DeviceData(0x1000, 256),  # inputY + 0 bytes
        DeviceData(0x2000, 256),  # output + 0 bytes
    ]
    idata = [
        _input_bytes(inputX, 0, 256),
        _input_bytes(inputY, 0, 256),
        _input_bytes(output, 0, 256),
    ]
    optrs = [
        DeviceData(0x2000, 256),  # output + 0 bytes
    ]
    odata = [
        _output_bytes(output, 0, 256),
    ]
    olen = [256]
    config = DeviceConfig(
        config_values=config_values, iob_en=IOB_ENABLE,
        tile_en=TILE_ENABLE, data_ptr=iptrs + optrs,
    )
    stream = runtime.create_stream()
    await aux_stream(
        stream=stream, config=[config],
        iptrs=iptrs, idata=idata,
        optrs=optrs, odata=odata, olen=olen,
    )
    await stream.synchronize()
