# Generated by mapperPro for the current AuFORApro ADG.
# Host buffers are NumPy arrays; transfer lengths are bytes.
import numpy as np
from typing import List
from test_runif import DeviceConfig, DeviceData, DeviceRuntime, DeviceStream

CONFIG_VALUES = [
    0x1000, 0xaba0, 0x1601,
    0xffea, 0xefff, 0x1602,
    0xffef, 0xefff, 0x1603,
    0xffef, 0xefff, 0x1604,
    0xffef, 0xefff, 0x1605,
    0xffef, 0xefff, 0x1606,
    0x000f, 0x0000, 0x1607,
    0x0000, 0x0000, 0x1608,
    0x0000, 0x0000, 0x1609,
    0x0000, 0x0000, 0x160a,
    0x0000, 0x0000, 0x160b,
    0x0000, 0x0000, 0x160c,
    0x1820, 0x038a, 0x160d,
    0x0000, 0x0000, 0x160e,
    0x0000, 0x0000, 0x160f,
    0x0000, 0x0000, 0x1610,
    0x0000, 0x0000, 0x1611,
    0x0000, 0x0000, 0x1612,
    0x0000, 0xcf00, 0x1613,
    0xcc12, 0x54f9, 0x1614,
    0x8b60, 0x8a7c, 0x1615,
    0xb51b, 0xe0fe, 0x1616,
    0xffff, 0x007f, 0x1617,
    0x0000, 0x0100, 0x1618,
    0x0000, 0x0100, 0x1619,
    0x0000, 0x0100, 0x161a,
    0x0000, 0x0100, 0x161b,
    0x0000, 0x0100, 0x161c,
    0x0000, 0x0100, 0x161d,
    0x0000, 0x0100, 0x161e,
    0x0000, 0x0100, 0x161f,
    0x0000, 0x0100, 0x1620,
    0x0000, 0x0100, 0x1621,
    0x0000, 0x0100, 0x1622,
    0x0000, 0x0100, 0x1623,
    0x0000, 0x0100, 0x1624,
    0x0000, 0x0100, 0x1625,
    0x0000, 0x0100, 0x1626,
    0x0000, 0x0100, 0x1627,
    0x0000, 0x0100, 0x1628,
    0x0000, 0x0100, 0x1629,
    0x0000, 0x0100, 0x162a,
    0x0000, 0x0100, 0x162b,
    0x0000, 0x0100, 0x162c,
    0x0000, 0x0100, 0x162d,
    0x0000, 0x0100, 0x162e,
    0x0000, 0x0100, 0x162f,
    0x0000, 0x0100, 0x1630,
    0x0000, 0x0200, 0x17c0,
    0x0002, 0x0000, 0x1800,
    0x0000, 0x0180, 0x1d00,
    0x0000, 0x0008, 0x1d40,
    0x0200, 0x0000, 0x2240,
    0x0000, 0x0000, 0x2280,
    0x2400, 0x1000, 0x2580,
    0x0000, 0x0000, 0x2581,
    0x0000, 0x1020, 0x2582,
    0x0400, 0x0000, 0x2583,
    0x2000, 0x1000, 0x2600,
    0x0000, 0x0000, 0x2601,
    0x0000, 0x8020, 0x2602,
    0x0000, 0x0000, 0x2603,
]
IOB_ENABLE = [0x0, 0x5]
TILE_ENABLE = [0x01]

def _input_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    data = np.ascontiguousarray(array).view(np.uint8).reshape(-1)
    if data.nbytes < offset + size:
        raise ValueError(f'input buffer has {data.nbytes} bytes, needs {offset + size}')
    return data[offset:offset + size]

def _output_bytes(array: np.ndarray, offset: int, size: int) -> np.ndarray:
    if not isinstance(array, np.ndarray) or not array.flags.c_contiguous:
        raise TypeError('output buffers must be C-contiguous NumPy arrays')
    if not array.flags.writeable or array.nbytes < offset + size:
        raise ValueError(f'output buffer has {array.nbytes} writable bytes, needs {offset + size}')
    return array.view(np.uint8).reshape(-1)[offset:offset + size]

async def aux_stream(
    stream: DeviceStream, config: List[DeviceConfig],
    iptrs: List[DeviceData], idata: List[np.ndarray],
    optrs: List[DeviceData], odata: List[np.ndarray], olen: List[int],
):
    await stream.apply(config)
    await stream.config(config_id=0)
    for ptr, data in zip(iptrs, idata):
        await stream.memcpyHostToDevice(
            d_data=ptr, h_data=data, size=ptr.size
        )
    await stream.execution_start()
    for ptr, data, size in zip(optrs, odata, olen):
        await stream.memcpyDeviceToHost(
            d_data=ptr, h_data=data, size=size
        )
    await stream.release()

async def logsigmod(runtime: DeviceRuntime, input: np.ndarray, output: np.ndarray):
    config_values = list(CONFIG_VALUES)
    iptrs = [
        DeviceData(0x6000, 64),  # input + 0 bytes
    ]
    idata = [
        _input_bytes(input, 0, 64),
    ]
    optrs = [
        DeviceData(0x7000, 64),  # output + 0 bytes
    ]
    odata = [
        _output_bytes(output, 0, 64),
    ]
    olen = [64]
    config = DeviceConfig(
        config_values=config_values, iob_en=IOB_ENABLE,
        tile_en=TILE_ENABLE, data_ptr=iptrs + optrs,
    )
    stream = runtime.create_stream()
    await aux_stream(
        stream=stream, config=[config],
        iptrs=iptrs, idata=idata,
        optrs=optrs, odata=odata, olen=olen,
    )
    await stream.synchronize()
